apiVersion: v1
kind: Secret
metadata: { name: {{ .Release.Name }}-secrets }
type: Opaque
stringData:
  postgresPassword: {{ .Values.secrets.postgresPassword | quote }}
  redisPassword: {{ .Values.secrets.redisPassword | quote }}
  kek: {{ .Values.secrets.kek | quote }}
